import json
from pathlib import Path

p = Path(r'c:\Users\maria\Documents\GitHub\MaCAD26-G01-DataEncoding\notebooks\06_CityClassification.ipynb')
data = json.loads(p.read_text(encoding='utf-8'))

def cell_text(cell):
    return '\n'.join(cell.get('source', []))


def find_cell(snippet):
    for cell in data['cells']:
        if isinstance(cell, dict) and snippet in cell_text(cell):
            return cell
    raise KeyError(f'Could not find cell containing: {snippet!r}')

find_cell("PBF_PATH = Path(BASE_DIR) / 'geofabrik'")['source'] = [
    '# ── EDIT HERE ────────────────────────────────────────────────────────────────',
    'PLACE = "Digbeth, Birmingham, UK"   # Any OSM place string',
    '#London Borough of Islington, London, UK',
    '#Raval, Barcelona, Spain',
    '#Eixample, Barcelona, Spain',
    '#Salamanca, Madrid, Spain',
    '#Belleville, Paris, France',
    '#Altona, Hamburg, Germany',
    '#Ehrenfeld, Cologne, Germany',
    '#Trastevere, Rome, Italy',
    '#De Pijp, Amsterdam, Netherlands',
    '#Mouraria, Lisbon, Portugal',
    '',
    '#Digbeth, Birmingham, UK',
    '#Northern Quarter, Manchester, UK',
    '#Ancoats, Manchester, UK',
    '#Jewellery Quarter, Birmingham, UK',
    '#Headingley, Leeds, UK',
    '#Kelham Island, Sheffield, UK',
    '#Stokes Croft, Bristol, UK',
    '#Lace Market, Nottingham, UK',
    '',
    '',
    '# ─────────────────────────────────────────────────────────────────────────────',
    '',
    'import os',
    'import sys',
    'from pathlib import Path',
    '',
    "BASE_DIR   = r'C:\\Users\\maria\\Documents\\GitHub\\MaCAD26-G01-DataEncoding'",
    "MODEL_DIR  = os.path.join(BASE_DIR, 'models')",
    "OUTPUT_DIR = os.path.join(BASE_DIR, 'csv')",
    '',
    '# Make the repository root importable so `from scripts...` works regardless of launch directory.',
    'ROOT_DIR = Path(BASE_DIR)',
    'if str(ROOT_DIR) not in sys.path:',
    '    sys.path.insert(0, str(ROOT_DIR))',
    '',
    '# Prefer the local Geofabrik extract so building-derived features are available.',
    "PBF_PATH = Path(BASE_DIR) / 'geofabrik' / 'england-260610.osm.pbf'",
    'if not PBF_PATH.exists():',
    '    PBF_PATH = None',
    'else:',
    '    PBF_PATH = str(PBF_PATH)',
    '',
    "print(f'Target place : {PLACE}')",
    "print(f'Model dir    : {MODEL_DIR}')",
    "print(f'Output dir   : {OUTPUT_DIR}')",
]

find_cell("place_candidates = [', '.join(place_parts[i:]) for i in range(len(place_parts))]")['source'] = [
    "print(f'Fetching street network for: {PLACE}')",
    "place_parts = [part.strip() for part in PLACE.split(',') if part.strip()]",
    "place_candidates = [', '.join(place_parts[i:]) for i in range(len(place_parts))]",
    'place_candidates.append(PLACE)',
    '',
    'def _repair_polygon(geom):',
    '    if geom is None or geom.is_empty:',
    '        return None',
    "    if geom.geom_type not in ('Polygon', 'MultiPolygon'):",
    '        geom = geom.envelope',
    '    try:',
    '        if not geom.is_valid:',
    '            repaired = geom.buffer(0)',
    '            if repaired is not None and not repaired.is_empty:',
    '                geom = repaired',
    '    except Exception:',
    '        pass',
    '    if geom is None or geom.is_empty:',
    '        return None',
    "    if geom.geom_type not in ('Polygon', 'MultiPolygon'):",
    '        geom = geom.envelope',
    '    return geom',
    '',
    'study_area_ll = None',
    'selected_query = None',
    '',
    'for query in place_candidates:',
    '    try:',
    '        candidate = ox.geocode_to_gdf(query)',
    '    except Exception as exc:',
    "        print(f'  ⚠ Geocoding failed for {query!r}: {exc}')",
    '        continue',
    '',
    '    geom = _repair_polygon(candidate.geometry.iloc[0])',
    "    if geom is not None and geom.geom_type in ('Polygon', 'MultiPolygon') and not geom.is_empty:",
    '        study_area_ll = candidate.copy()',
    "        study_area_ll.iloc[0, study_area_ll.columns.get_loc('geometry')] = geom",
    '        selected_query = query',
    '        break',
    '',
    'if study_area_ll is None:',
    '    raise TypeError(',
    '        f"Could not resolve a usable polygon boundary for {PLACE!r}. "',
    '        "Try a broader place name such as the containing city or borough."',
    '    )',
    '',
    'if selected_query != PLACE:',
    '    print(f"  Using polygon boundary from fallback query: {selected_query!r}")',
    '',
    'FEATURE_QUERY = selected_query or PLACE',
    'print(f\'  Using feature query: {FEATURE_QUERY!r}\')',
    '',
    'boundary = study_area_ll.geometry.iloc[0]',
    "G = ox.graph_from_polygon(boundary, network_type='drive')",
    'edges = ox.graph_to_gdfs(G, nodes=False).to_crs(CRS_METRIC)',
    'nodes_gdf = ox.graph_to_gdfs(G, edges=False).to_crs(CRS_METRIC)',
    'study_area = study_area_ll.to_crs(CRS_METRIC)',
    'boundary = study_area.geometry.iloc[0]',
    '',
    'edges = edges.reset_index()',
    "print(f'✓ {len(edges):,} street segments fetched')",
]

find_cell("def _repair_geometries(geoms):")['source'] = [
    'def _repair_geometries(geoms):',
    '    repaired = []',
    '    for geom in geoms:',
    '        if geom is None or geom.is_empty:',
    '            repaired.append(geom)',
    '            continue',
    '        if not geom.is_valid:',
    '            try:',
    '                geom = geom.buffer(0)',
    '            except Exception:',
    '                pass',
    '        repaired.append(geom)',
    '    return gpd.GeoSeries(repaired, index=geoms.index, crs=geoms.crs)',
    '',
    '',
    'def _is_uk_or_england_query(place: str) -> bool:',
    '    p = place.strip().lower()',
    '    return (',
    "        p.endswith(', uk')",
    "        or p.endswith(', united kingdom')",
    "        or p.endswith(', england')",
    "        or ', uk' in p",
    "        or ', united kingdom' in p",
    "        or ', england' in p",
    "        or 'london borough of' in p",
    "        or ('borough' in p and ', london, uk' in p)",
    '    )',
    '',
    '',
    'def _load_from_osm(place, crs):',
    "    print('  Trying OSM (Overpass)...')",
    "    buildings = ox.features_from_place(place, tags={'building': True})",
    "    buildings = buildings[buildings.geometry.geom_type.isin(['Polygon', 'MultiPolygon'])].copy()",
    '    buildings = buildings.to_crs(crs)',
    "    buildings['geometry'] = _repair_geometries(buildings.geometry)",
    '    buildings = buildings[buildings.geometry.notna() & ~buildings.geometry.is_empty].copy()',
    "    print(f'  ✓ OSM: {len(buildings):,} building footprints')",
    '    return buildings',
    '',
    '',
    'def _load_from_pbf(place, crs, pbf_path):',
    '    if not pbf_path or not Path(pbf_path).exists():',
    "        raise FileNotFoundError('Local PBF file not found')",
    '',
    "    print('  Trying local PBF...')",
    '    from scripts.building_loader import get_borough_buildings',
    '',
    '    buildings = get_borough_buildings(place, pbf_path=pbf_path, allow_overpass_fallback=False)',
    '    if buildings is None or buildings.empty:',
    "        raise RuntimeError('No building footprints returned from PBF')",
    '',
    '    buildings = buildings.to_crs(crs)',
    "    buildings['geometry'] = _repair_geometries(buildings.geometry)",
    '    buildings = buildings[buildings.geometry.notna() & ~buildings.geometry.is_empty].copy()',
    "    print(f'  ✓ PBF: {len(buildings):,} building footprints')",
    '    return buildings',
    '',
    '',
    'def fetch_buildings(place, crs, pbf_path=None):',
    '    """PBF-first for UK/England places; OSM-first elsewhere."""',
    '    pbf_first = _is_uk_or_england_query(place)',
    '',
    '    if pbf_first:',
    '        try:',
    "            print('  UK/England place detected — prioritizing local PBF...')",
    '            return _load_from_pbf(place, crs, pbf_path)',
    '        except Exception as e:',
    "            print(f'  PBF failed: {e}')",
    "            print('  Falling back to OSM (Overpass)...')",
    '            try:',
    '                return _load_from_osm(place, crs)',
    '            except Exception as e2:',
    "                print(f'  OSM failed: {e2}')",
    "                print('  ⚠ No building footprints available — enclosure/visibility/land-use will be NaN')",
    '                return None',
    '',
    '    try:',
    '        return _load_from_osm(place, crs)',
    '    except Exception as e:',
    "        print(f'  OSM failed: {e}')",
    '        if pbf_path and Path(pbf_path).exists():',
    '            try:',
    "                print('  Falling back to local PBF...')",
    '                return _load_from_pbf(place, crs, pbf_path)',
    '            except Exception as e2:',
    "                print(f'  PBF also failed: {e2}')",
    "        print('  ⚠ No building footprints available — enclosure/visibility/land-use will be NaN')",
    '        return None',
    '',
    '',
    'buildings = fetch_buildings(FEATURE_QUERY, CRS_METRIC, PBF_PATH)',
]

find_cell('Default: OSM (Overpass) first, then local PBF fallback.')['source'] = [
    '## Step 4: Fetch Building Footprints',
    '',
    'Default: OSM (Overpass) first, then local PBF fallback.',
    'UK/England places: local England PBF first, then OSM fallback if needed.',
]

find_cell("MAPILLARY_DIR = Path(BASE_DIR) / 'notebooks' / 'data' / 'mapillary'")['source'] = [
    "MAPILLARY_DIR = Path(BASE_DIR) / 'notebooks' / 'data' / 'mapillary'",
    'MAPILLARY_LIGHTS_FILES = {',
    "    'raval, barcelona, spain': 'mapillary_lights_raval_barcelona.csv',",
    "    'eixample, barcelona, spain': 'mapillary_lights_eixample_barcelona.csv',",
    "    'belleville, paris, france': 'mapillary_lights_belleville_paris.csv',",
    "    'trastevere, rome, italy': 'mapillary_lights_trastevere_rome.csv',",
    "    'salamanca, madrid, spain': 'mapillary_lights_salamanca_madrid.csv',",
    "    'london borough of islington, london, uk': 'mapillary_lights_islington_london.csv',",
    "    'islington, london, uk': 'mapillary_lights_islington_london.csv',",
    '}',
    '',
    '',
    'def _load_mapillary_lights(place: str) -> gpd.GeoDataFrame | None:',
    '    csv_name = MAPILLARY_LIGHTS_FILES.get(place.strip().lower())',
    '    if csv_name is None:',
    "        print(f'  ⚠ No Mapillary CSV mapping found for {place!r} — lighting set to 0')",
    '        return None',
    '',
    '    csv_path = MAPILLARY_DIR / csv_name',
    '    if not csv_path.exists():',
    "        print(f'  ⚠ Mapillary CSV not found: {csv_path} — lighting set to 0')",
    '        return None',
    '',
    '    df = pd.read_csv(csv_path)',
    '    df.columns = df.columns.str.lower().str.strip()',
    '',
    "    lon_col = next((c for c in df.columns if c.startswith('lon')), None)",
    "    lat_col = next((c for c in df.columns if c.startswith('lat')), None)",
    '    if lon_col is None or lat_col is None:',
    "        raise ValueError(f'Could not find lon/lat columns in {csv_path}. Found: {list(df.columns)}')",
    '',
    '    gdf = gpd.GeoDataFrame(',
    '        df,',
    '        geometry=gpd.points_from_xy(df[lon_col], df[lat_col]),',
    "        crs='EPSG:4326',",
    '    ).to_crs(CRS_METRIC)',
    '',
    "    print(f'  ✓ Loaded {len(gdf):,} Mapillary lights from {csv_path.name}')",
    '    return gdf',
    '',
    '',
    'try:',
    "    print('Loading Mapillary street lights...')",
    '    lamps_gdf = _load_mapillary_lights(FEATURE_QUERY)',
    '    if lamps_gdf is None or lamps_gdf.empty:',
    "        edges['lighting'] = 0",
    '    else:',
    '        lamp_counts = []',
    '        for buf_geom in segs_buf.geometry:',
    '            count = lamps_gdf.geometry.within(buf_geom).sum()',
    '            lamp_counts.append(int(count))',
    "        edges['lighting'] = lamp_counts",
    'except Exception as e:',
    "    print(f'  ⚠ Mapillary lamp load failed: {e} — lighting set to 0')",
    "    edges['lighting'] = 0",
    '',
    'print(f\'  Lighting range: {edges["lighting"].min()} – {edges["lighting"].max()}\')',
]

find_cell("RAIL_TAGS = {")['source'] = [
    'RAIL_TAGS = {',
    "    'railway': ['subway_entrance', 'station', 'tram_stop'],",
    "    'public_transport': 'stop_position',",
    '}',
    'BUS_TAGS = {',
    "    'highway': 'bus_stop',",
    "    'public_transport': 'platform',",
    '}',
    '',
    'def _nearest_dist(edges_proj, stops_gdf, col_name):',
    '    segment_points = edges_proj.geometry.apply(',
    "        lambda g: g.interpolate(0.5, normalized=True)",
    "        if g.geom_type in ('LineString', 'MultiLineString') else g.centroid",
    '    )',
    '    if stops_gdf is None or stops_gdf.empty:',
    '        edges_proj[col_name] = np.nan',
    '        return edges_proj',
    '    stop_coords = np.array([(g.x, g.y) for g in stops_gdf.geometry])',
    '    dists = []',
    '    for mp in segment_points:',
    '        d = np.sqrt(((stop_coords - [mp.x, mp.y]) ** 2).sum(axis=1)).min()',
    '        dists.append(round(float(d), 2))',
    '    edges_proj[col_name] = dists',
    '    return edges_proj',
    '',
    'def fetch_stops(tags, label, place, crs):',
    '    try:',
    '        gdf = ox.features_from_place(place, tags=tags)',
    "        gdf['geometry'] = gdf.geometry.apply(",
    "            lambda g: g.centroid if g.geom_type != 'Point' else g",
    '        )',
    "        gdf = gdf[['geometry']].to_crs(crs).drop_duplicates('geometry')",
    "        print(f'  {label}: {len(gdf):,} stops')",
    '        return gdf',
    '    except Exception as e:',
    "        print(f'  ⚠ {label} fetch failed: {e}')",
    '        return None',
    '',
    "print('Fetching transit stops...')",
    "rail = fetch_stops(RAIL_TAGS, 'Rail', FEATURE_QUERY, CRS_METRIC)",
    "bus  = fetch_stops(BUS_TAGS,  'Bus',  FEATURE_QUERY, CRS_METRIC)",
    '',
    "edges = _nearest_dist(edges, rail, 'dist_to_rail_m')",
    "edges = _nearest_dist(edges, bus,  'dist_to_bus_m')",
    '',
    '# Combined: use the closer of the two stops as the proximity score',
    "edges['public_transport_proximity_m'] = edges[['dist_to_rail_m', 'dist_to_bus_m']].min(axis=1)",
    'print(f\'✓ Transport proximity range: {edges["public_transport_proximity_m"].min():.1f} – {edges["public_transport_proximity_m"].max():.1f} m\')',
]

p.write_text(json.dumps(data, ensure_ascii=False, indent=4), encoding='utf-8')
print('updated', p)
